# Copyright Antti Kultanen <antti.kultanen@molukki.com>
# nflog_dns is licensed under GNU GPL v2 or later; see LICENSE file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "13:37"
      timezone: "Europe/Helsinki"
    groups:
      actions:
        patterns:
          - "actions/*"
      codeql:
        patterns:
          - "github/codeql-action*"

