#!/bin/sh
set -e

# Check if we're using systemd or sysvinit and start the daemon accordingly
if [ -n "$(which systemctl 2>/dev/null)" ]
then
	systemctl --quiet is-active nflog_dns && systemctl restart nflog_dns || systemctl start nflog_dns
elif [ -x /etc/init.d/nflog_dns ]
then
	/etc/init.d/nflog_dns status > /dev/null 2>&1 && /etc/init.d/nflog_dns restart || /etc/init.d/nflog_dns start
fi
