#!/bin/sh
# postrm script for nflog-dns
#
# Removes dedicated unprivileged user on purge.

set -e

NFLOG_DNS_USER="_nflog-dns"

case "${1}" in
	purge)
		if getent passwd "${NFLOG_DNS_USER}" >/dev/null 2>&1
		then
			deluser --quiet --system "${NFLOG_DNS_USER}" >/dev/null || true
		fi
		if getent group "${NFLOG_DNS_USER}" >/dev/null 2>&1
		then
			delgroup --quiet --system "${NFLOG_DNS_USER}" >/dev/null || true
		fi
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

	*)
		echo "postrm called with unknown argument ${1}" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
