#!/bin/sh
# postinst script for nflog-dns
#
# Creates a dedicated unprivileged user to drop privileges to.

set -e

NFLOG_DNS_USER="_nflog-dns"

case "${1}" in
	configure)
		if ! getent passwd "${NFLOG_DNS_USER}" >/dev/null 2>&1
		then
			adduser --quiet --system --disabled-login \
				--no-create-home --home /nonexistent \
				--shell /usr/sbin/nologin \
				--group "${NFLOG_DNS_USER}"
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument ${1}" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
