#!/bin/bash

### BEGIN INIT INFO
# Provides:          nflog_dns
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DNS reply logger
# Description:       NFLOG-based userland DNS reply logger
### END INIT INFO

# Author: Antti Kultanen <pyksy at pyksy dot fi>

PATH="/sbin:/bin:/usr/sbin:/usr/bin"
DAEMON="/usr/local/sbin/nflog_dns"
NAME="nflog_dns"
DESC="NFLOG-based userland DNS reply logger"
DEFAULT="/etc/default/${NAME}"
PIDFILE="/run/${NAME}.pid"

source /lib/lsb/init-functions

[ -f "${DEFAULT}" ] && source "${DEFAULT}"
[ -x "${DAEMON}" ] || exit 0

check_running() {
	if status_of_proc "${DAEMON}" "${DESC}" > /dev/null
	then
		log_progress_msg "already running"
		log_end_msg 0
		exit 0
	fi
}

start_nflog_dns() {
	log_daemon_msg "Starting ${DESC}" "$NAME"

	check_running

	if start-stop-daemon --start \
		--pidfile "${PIDFILE}" \
		--make-pidfile \
		--background \
		--exec "${DAEMON}" -- ${OPTIONS}
	then
		log_success_msg
	else
		log_failure_msg
		exit 1
	fi
}

stop_nflog_dns() {
	log_daemon_msg "Stopping ${DESC}" "$NAME"

	if start-stop-daemon --stop \
		--pidfile "${PIDFILE}" \
		--remove-pidfile \
		--signal HUP \
		--quiet \
		--exec "${DAEMON}"
	then
		log_success_msg
	else
		log_failure_msg
		return 1
	fi
}

case "${1}" in
	start)
		start_nflog_dns
	;;
	stop)
		stop_nflog_dns || exit ${?}
	;;
	restart)
		stop_nflog_dns
		start_nflog_dns
	;;
	status)
		status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" && exit 0 || exit ${?}
	;;
	*)
		log_action_msg "Usage: ${0} {start|stop|restart|status}" >&2
	;;
esac
