#!/bin/bash

### BEGIN INIT INFO
# Provides:          nflog_dns
# Required-Start:    $network $local_fs $syslog
# Required-Stop:     $network $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DNS reply logger
# Description:       NFLOG-based userland DNS reply logger
### END INIT INFO

# Author: Antti Kultanen <antti.kultanen@molukki.com>
# nflog_dns is licensed under GNU GPL v2 or later; see LICENSE file

PATH="/sbin:/bin:/usr/sbin:/usr/bin"
DAEMON="/usr/local/sbin/nflog_dns"
NAME="nflog_dns"
DESC="NFLOG-based userland DNS reply logger"
DEFAULT="/etc/default/${NAME}"
PIDFILE="/run/${NAME}.pid"

source /lib/lsb/init-functions

[ -f "${DEFAULT}" ] && source "${DEFAULT}"
[ -x "${DAEMON}" ] || exit 5

check_running() {
	status_of_proc "${DAEMON}" "${DESC}" > /dev/null && return 0 || return 1
}

start_nflog_dns() {
	log_daemon_msg "Starting ${DESC}" "$NAME"

	if check_running
	then
		log_progress_msg "already running"
		log_end_msg 0
		return 0
	fi

	if start-stop-daemon --start \
		--pidfile "${PIDFILE}" \
		--make-pidfile \
		--background \
		--quiet \
		--exec "${DAEMON}" -- ${OPTIONS}
	then
		log_end_msg 0
		return 0
	else
		log_end_msg 1
		return 1
	fi
}

stop_nflog_dns() {
	log_daemon_msg "Stopping ${DESC}" "$NAME"

	if start-stop-daemon --stop \
		--pidfile "${PIDFILE}" \
		--remove-pidfile \
		--retry=HUP/5/TERM/10/KILL/5 \
		--quiet \
		--exec "${DAEMON}"
	then
		log_success_msg
	else
		log_failure_msg
		return 1
	fi
}

case "${1}" in
	start)
		start_nflog_dns || exit ${?}
	;;
	stop)
		stop_nflog_dns || exit ${?}
	;;
	restart)
		stop_nflog_dns
		# Wait for process to actually exit
		for i in {1..10}; do
			status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" >/dev/null 2>&1 || break
			sleep 1
		done
		start_nflog_dns
	;;
	status)
		status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}"
		exit ${?}
	;;
	*)
		log_action_msg "Usage: ${0} {start|stop|restart|status}" >&2
	;;
esac
