name: Build nflog_dns

on:
  push:
    branches:
    - '**'
    tags:
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build and test dependencies
      run: sudo apt-get -y install libtins-dev libnetfilter-log-dev libspdlog-dev python3

    - name: Update version.h if tagged
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "#define PROGRAM_VERSION \"$VERSION\""

    - name: Compile binary
      run: make

    - name: Run tests
      run: sudo bash test/run_tests.sh

    - name: Install binary
      run: sudo make install
